replicaCount: 1
deploymentName: simpleservice
namespace: simpleservice
image:
  repository: wlanboy/simpleservice
  tag: latest
  pullPolicy: Always

service:
  port: 8201
  targetPort: 8080

persistence:
  enabled: true
  size: 100Mi
  # leer lassen, um die Default-StorageClass des Clusters zu verwenden
  storageClass: ""

ingress:
  # istio | traefik | none
  controller: istio
  hosts:
    - simpleservice.tp.lan
    - simpleservice.gmk.lan
    - simpleservice.localhost

istio:
  gateway: simpleservice-gateway
  gatewayNamespace: "istio-ingress"

traefik:
  entryPoints:
    - web
    - websecure

certmanager:
  enabled: true
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: simpleservice-tls
